### ISSUE TITLE
Better Logging of error causes

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-tests#47] opened 2017-04-05 20:53 UTC
I ran a local job and I think it had an error, since it didn't create all the files in `data_dir`. However, the `slurm.out` file didn't state where the error occurred. It would be helpful for the slurm output to mention where the error likely occurred. Increased logging may be helpful. If there is already a way to get logging at the source of the error, that would be helpful.

**Comment by KEHANG** [comment] 2017-04-06 00:13
@goldmanm I've looked at your RMG-tests directory. I think I know the cause. If you fetch the newest RMG-tests, it should work

**Comment by goldmanm** [comment] 2017-06-27 03:03
fixed

**Comment by goldmanm** [comment] 2017-06-27 03:04
actually, while the original cause might be fixed, I am not sure if better bug detection and logging has been implemented.

**Comment by goldmanm** [comment] 2017-06-27 03:08
One additional thing that could be beneficial when logging is to state which branch is throwing an exception (the master or new branch). I got confused on a recent run. When the master branch was throwing an exception and crashing the RMG-tests job, I thought it was the new branch that was failing. Maybe I just missed where the log mentioned which RMG version was crashing.

**Comment by JacksonBurns** [comment] 2023-04-14 18:52
The changes described in #86 always treat the main branch as "stable" and clearly indicate that the proposed changes on another branch (the "dynamic" changes) are responsible for regression failures. Closing as completed.

**Closed by JacksonBurns** 2023-04-14 18:52 UTC
